apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nexus-app
  namespace: argocd
spec:
  project: default
  source:
    # CHANGE THIS TO YOUR GITHUB REPO URL
    repoURL: https://github.com/kelyonnnn17/nexus.git
    targetRevision: dev_shubhang
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: nexus
  syncPolicy:
    automated:
      prune: true
      selfHeal: true