apiVersion: v1
kind: Service
metadata:
  name: nexus-service
spec:
  selector:
    app: nexus-app
  ports:
    - protocol: TCP
      port: 80         # External Port (Standard Web)
      targetPort: 5050 # Forward to your Container Port
  type: LoadBalancer