apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: nexus-pod-kill
  namespace: chaos-mesh
spec:
  action: pod-kill
  mode: fixed-percent
  value: "50"
  selector:
    namespaces:
      - nexus
    labelSelectors:
      app: nexus-app
  duration: "1m"